AWSTemplateFormatVersion: 2010-09-09
Description: Template to create EC2 and attach EBS volume

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-008fe2fc65df48dac  # Replace your image id
      InstanceType: t2.micro
      SubnetId: subnet-06896bc0849ecea5d  # Replace subnet
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: web-server
        - Key: Project
          Value: AWS CloudFormation Step by Step
  
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web servers
      VpcId: vpc-09610f5a9438fd239 # Replace VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0' 

  EBSVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      Size: 15 
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
      Tags:
        - Key: Name
          Value: EBSVolume

  VolumeAttachment:
    Type: 'AWS::EC2::VolumeAttachment'
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref EBSVolume
      Device: /dev/sdf  

Outputs:
  InstanceId:
    Description: Instance ID of the newly created EC2 instance
    Value: !Ref EC2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
