# This template creates the EC2 Instace

AWSTemplateFormatVersion: 2010-09-09
Description: My first step to learning CloudFormation

Parameters:
  Sample:
    Type: String
    Description: testing
    Default: ""

Resources:
  MyWebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:  ami-008fe2fc65df48dac  # To be replaced with the supported AMI  id for the region, this is for us-west-2
      InstanceType: t2.micro
      SubnetId: subnet-06896bc0849ecea5d  # To be replaced with the subnet id from your environment
      Tags:
        - Key: Name
          Value: web-server
        - Key: Project
          Value: My First EC2 Creation Through CloudFormation





