AWSTemplateFormatVersion: 2010-09-09
Description: Template to create EC2 instance and install Python

Parameters:
  KeyName:
    Description: Name of the EC2 key pair to associate with the instance
    Type: AWS::EC2::KeyPair::KeyName # Create a key pair and use the key while creating the stack
    # Type can be string here, But when you use AWS defined types, Stack creation will list all available keys
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-008fe2fc65df48dac  # Replace your AMI ID based on your region
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      KeyName: !Ref KeyName
      UserData:
        Fn::Base64:  | # Function to encode given data to Base64, | indicates you can have multi liner
          #!bin/bash
          sudo apt install unzip
          sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo unzip awscliv2.zip
          sudo ./aws/install
          yes | sudo apt update
          yes | sudo apt install apache2
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: Instance ID of the newly created EC2 instance
    Value: !Ref EC2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp




