# This templates add the functionality to link the EC2 and Security groups created in Step 1 and 2
# Make sure you replace the AMI ID, Subnet and VPC based on your region and environment

AWSTemplateFormatVersion: 2010-09-09
Description: Link the EC2 and Security Group Resources
Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-008fe2fc65df48dac
      InstanceType: t2.micro
      SubnetId: subnet-06896bc0849ecea5d
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: web-server
        - Key: Project
          Value: AWS CloudFormation Step by Step
  
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web servers
      VpcId: vpc-09610f5a9438fd239
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'